name: side_bar_custom
description: This package allows you to have a simple, fast and practical custom SideBar, in fact you will be able to customize almost everything. Seeing is believing.
version: 1.0.1
homepage: https://github.com/andreamainella98/side_bar_custom

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter: